@drizzle/store new typescript declarations
ConsenSys-archive/drizzle pull request #30
Opened 2019-09-23 17:54 UTC by MrRefactoring

2019-09-27 07:28 UTC, adrianmcli commented
@honestbonsai Do you think you can look at this when you have time?

2019-09-30 00:47 UTC, honestbonsai requested changes
Some small things, but anyways great work @MrRefactoring ! 

Though I guess a question would be how far do we want to go with the typing for this PR @adrianmcli . There's still a number of `any`. 

If we want to accept this as a jumping off point for future typing improvements I'm fine with that too, as it has already improved the existing types by quite a bit.

2019-09-30 00:47 UTC, honestbonsai commented on packages/store/index.d.ts
> +  export function accounts(state: any | undefined | null, action: IAction): any;
Maybe a type should be used here instead of repeating `any | undefined | null`.

2019-09-30 00:47 UTC, honestbonsai commented on packages/store/types/generateStore.d.ts
> +  drizzleOptions: any;
Can we use `IDrizzleOptions` here?

2019-09-30 00:47 UTC, honestbonsai commented on packages/store/index.d.ts
> +export namespace drizzleSagas {
Isn't `drizzleSagas` still an array though https://github.com/trufflesuite/drizzle/blob/develop/packages/store/src/index.js#L36.

Not sure why it was changed to a namespace.

2019-09-30 00:47 UTC, honestbonsai commented on packages/store/types/Drizzle.d.ts
> +  networkWhitelist?: any[];
Looks like this should be `number[]`

- https://web3js.readthedocs.io/en/v1.2.1/web3-eth-net.html#getid
- https://github.com/trufflesuite/drizzle/blob/0ee523028e72c80ca59477a86be11a58388729ae/packages/store/src/web3/web3Saga.js#L78
- https://github.com/trufflesuite/drizzle/blob/0ee523028e72c80ca59477a86be11a58388729ae/packages/store/src/drizzleStatus/drizzleStatusSaga.js#L28

2019-09-30 00:47 UTC, honestbonsai commented on packages/store/types/Drizzle.d.ts
> +  polls?: any;
Looks like its

```
{
  accounts?: number,
  blocks?: number
},
```

https://github.com/trufflesuite/drizzle/blob/6af1bf15356486e5b9e929bed80f847002d1bb9a/packages/store/README.md#options

2019-09-30 14:20 UTC, honestbonsai approved these changes
LGTM! Thanks for your contribution!

@adrianmcli This can be merged.

2019-09-30 21:33 UTC, adrianmcli commented
Thanks @honestbonsai and @MrRefactoring!

2019-09-30 21:33 UTC, merged